### ISSUE TITLE
License

### ISSUE THREAD

**Issue by russell** [ioquatix/zonestar-p802q-fan-duct#1]
Hey,

Sweet fan design.  I found it when i was searching for OpenFOAM simulations of 3d printer fans.  I found your video and it led me here.  I'm surprised that no one else has tried to do the same thing.  I'm going to try and re-run your simulation to see how it behaves on my full extruder assembly.

Anyway, I want to adapt your design to fit on my Prusa i3.  To be honest I'm almost done, but I can't really put it on thingiverse until you set a license.

Please consider putting a license that allows commercial use. I do 3d printing as a hobby I don't intend to make any money off your design.  But I think this design could be really valuable to the community, since you know, you actually designed and tested it, and didn't just guess how it would work.

Cheers,
Russell

**Comment by ioquatix** [comment]
The MIT license DOES allow commercial use. What exactly are you referring to?

**Comment by ioquatix** [comment]
Thanks for your nice comments :)

**Comment by ioquatix** [comment]
Let me know how you go getting it running in OpenFOAM. I think it would be good to update it for 4.x

**Comment by russell** [comment]
?  i put this comment in about almost year ago in July.  I see that you updated the readme to include a license last month.  This issue about not having an explicit license in the code base is now resolved.

**Comment by ioquatix** [comment]
My bad. I didn't realise the time frame of this request. My intent was always to use the MIT license, but as this was a work in progress I took ages to get around to making an actual README which is where I always put the license. Again, apologies.

**Comment by russell** [comment]
DW,  thanks for releasing this.  I'm going to take a look at it soon.  The photos you posted look impressive.
